### ISSUE TITLE
Problems to compile under openframeworks 9.0

### ISSUE THREAD

**Issue by laurenzrau91** [joshuajnoble/ofxBLEDevice#1]
Hi I tried to compile the example code with the new OF version and had trouble getting it running.

**Comment by joshuajnoble** [comment]
Thanks, could you post the output?

**Comment by joshuajnoble** [comment]
Ok I think https://github.com/joshuajnoble/ofxBLEDevice/commit/abe170382a91f505c4d4cb629ba4e454a5b2b173 fixes it?

**Comment by laurenzrau91** [comment]
That´s the message I get: 
ld: '/Users/.../of_v0.9.0_FAT/libs/openFrameworksCompiled/lib/ios/libofxiOS_iphoneos_Debug.a(ofxiOSImagePicker.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

When I set ENABLE_BITCODE to No it will compile without error, but the app is basily empty then.

**Comment by joshuajnoble** [comment]
You do want bitcode enabled so I wonder if this is a problem with the iOS+OFLib project within the project file? Do all of the other projects work fine for you?

**Comment by laurenzrau91** [comment]
Ok I think abe1703 acctually did solve the problem.
Thanks a lot!

**Comment by joshuajnoble** [comment]
Great!
