### ISSUE TITLE
Is there a way to compile to OS X too?

### ISSUE THREAD

**Issue by dimitre** [joshuajnoble/ofxBLEDevice#5]
I'm trying to compile the example in OS X and getting an error. I suppose it is just something minor related to objective-c / c compiler settings
![screen shot 2016-10-08 at 10 00 32 pm](https://cloud.githubusercontent.com/assets/58289/19216837/b17d3254-8da2-11e6-84d9-21705d3cc664.png)

**Comment by joshuajnoble** [comment]
Whoa, sorry for the slow response. Unfortunately this is only iOS specific b/c of how the BLE functionality is implemented.
