### ISSUE TITLE
Possible to connect to a Mi band?

### ISSUE THREAD

**Issue by slasktotten** [joshuajnoble/ofxBLEDevice#6]
Hi,

I was wondering if it would be possible use this library to connect to other BLE devices (in my case a Mi band in order to grab heart rate data) apart from the arduino?
Apologies if the qustion is stupid but have never worked with bluetooth or BLE before.

Best,
Gustaf

**Comment by joshuajnoble** [comment]
Should be, yes, but you'd need a lot of info about the services and functionality of the Mi band that I don't have at present
